### ISSUE TITLE
$gr0 is not a IntRegs register.

### ISSUE THREAD

**Issue by luxufan** [kkkobbb/llvm-comet2#2]
<img width="455" alt="截屏2020-06-05 下午3 33 30" src="https://user-images.githubusercontent.com/37958561/83849381-e979ae00-a741-11ea-834d-906f1c095b92.png">
for the ll code in the above, the llc will issue error, which is 
<img width="769" alt="截屏2020-06-05 下午3 34 13" src="https://user-images.githubusercontent.com/37958561/83849449-03b38c00-a742-11ea-8fd2-354150b53011.png">

**Comment by kkkobbb** [comment]
First I added GR0 to IntRegs RegisterClass and ran llc.
Then the following error occurred:
```
Use of %2 does not have a corresponding definition on every path:
32r %2:intregs = LDREG %2:intregs
LLVM ERROR: Use not jointly dominated by defs.
```
The root cause of the error is that memory load instruction generation was not working. And fixed.

**Comment by luxufan** [comment]
Are you working with llvm?
And can I make a friend with you? We can add each other as Facebook friend or other social software



发自我的iPhone


------------------ Original ------------------

**Comment by kkkobbb** [comment]
I only have a github account. I'm glad to have a new friend who is interested in llvm
